server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaohuaiy/ghyspringcloud.git
          search-paths: config
          username: 2338944731@qq.com
          password: 2338944731@qq.com
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/